tech_talent_store/config/routes.rb
Rails.application.routes.draw do
  get 'cart/aad_to_cart'

  get 'cart/view_order'

  get 'cart/checkout'

  devise_for :users
  root 'storefront#all_items'

  get '/categorical' => 'storefront#items_by_category' 

  get '/branding' => 'storefront#items_by_brand'
  
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

tech_talent_store/app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

tech_talent_store/app/models/line_item.rb
class LineItem < ApplicationRecord
end

tech_talent_store/app/models/order.rb
class Order < ApplicationRecord
end

tech_talent_store/app/models/product.rb
class Product < ApplicationRecord

	mount_uploader :image, ImageUploader

	belongs_to :category

end

tech_talent_store/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

tech_talent_store/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :categories, :brands

  def categories
  	@categories = Category.order(:name)
  end

  def brands
  @brands = Product.pluck(:brand).sort.uniq
	end
end

tech_talent_store/app/controllers/cart_controller.rb
class CartController < ApplicationController
  def aad_to_cart
  end

  def view_order
  end

  def checkout
  end
end

tech_talent_store/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]


  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description, :brand, :rating, :category_id, :image)
    end
end

tech_talent_store/app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController


  def all_items
  	@products = Product.all
  end

  def items_by_category

  #to get to this page: catergorical_path(params[:category_id])

  @products = Product.where(category: params[:category_id])
  @category = Category.find(params[:category_id])

end

  def items_by_brand
  	@brand = Brand.find(params[:brand_id])
  end
end

tech_talent_store/app/helpers/cart_helper.rb
module CartHelper
end

tech_talent_store/app/helpers/products_helper.rb
module ProductsHelper
end

tech_talent_store/app/helpers/storefront_helper.rb
module StorefrontHelper
end

tech_talent_store/app/views/cart/aad_to_cart.html.erb
<h1>Cart#aad_to_cart</h1>
<p>Find me in app/views/cart/aad_to_cart.html.erb</p>

tech_talent_store/app/views/cart/checkout.html.erb
<h1>Cart#checkout</h1>
<p>Find me in app/views/cart/checkout.html.erb</p>

tech_talent_store/app/views/cart/view_order.html.erb
<h1>Cart#view_order</h1>
<p>Find me in app/views/cart/view_order.html.erb</p>

tech_talent_store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechTalentStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <% @categories.each do |category| %>
      <li><%= link_to category.name, categorical_path(category_id: category.id) %></li>
    <% end %>
  </ul>
</li>
      <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <% @brands.each do |brand| %>
      <li><%= link_to brand, branding_path(brand: brand) %></li>
    <% end %>
      <li><%= link_to 'All', root_path %></li>
  </ul>
</li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
  
    <div class="container">
  		<%= yield %>
	</div>
  </body>
</html>

tech_talent_store/app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :product_quantity %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="form-group">
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :product_brand %>
  </div>

  <div class="form-group">
    <%= form.label :rating %>
    <%= form.number_field :rating, id: :product_rating %>
  </div>


  <div class="form-group">
    <%= form.select :category_id, @categories.collect { |c| [ c.name, c.id ]}, {include_blank: "Please select a category" } %>
  </div>

  <div class="form-group">
    <strong>Upload Product Image: </strong>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

tech_talent_store/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

tech_talent_store/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Brand</th>
      <th>Rating</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= number_to_currency product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.description %></td>
        <td><%= product.brand %></td>
        <td><%= product.rating %></td>
        <td><%= product.category_id %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

tech_talent_store/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

tech_talent_store/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @product.rating %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

tech_talent_store/app/views/storefront/all_items.html.erb
<h1>Welcome to Tech Talent Store</h1>
<p>Give us your money!</p>

<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <div class="well">
        <% if product.image.url.nil? == false %>
          <p><%= image_tag product.image.url %></p>
        <% end %>
        <h3><%= link_to product.name, product %></h3>
        <p><%= number_to_currency product.price %></p>
        <p>
		  <a href="#" data-toggle="modal" data-target="#myModal_<%= product.id %>">
		    <span class="glyphicon glyphicon-plus"></span> Quick Info
		  </a>
		</p>
      </div>
    </div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

  <% end %>
</div>



<!-- Modal -->

tech_talent_store/app/views/storefront/items_by_brand.html.erb
<h1>Storefront#items_by_brand</h1>
<p>Find me in app/views/storefront/items_by_brand.html.erb</p>

tech_talent_store/app/views/storefront/items_by_category.html.erb
<h1>All of our <%= @category.name %></h1>

<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <div class="well center-it">
        <p><%= image_tag product.image.recreate_versions! if image.avatar? %></p>
        <h3><%= link_to product.name, product %></h3>
        <p><%= number_to_currency product.price %></p>
        <p>
          <a href='#' data-toggle="modal" data-target="#myModal_<%= product.id %>">
            <span class='glyphicon glyphicon-plus'></span>More Info
          </a>
        </p>
      </div>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            <h4 class="modal-title" id="myModalLabel"><%= product.name%></h4>
          </div>
          <div class="modal-body">
            <p><%= image_tag product.image.url(:thumb) %></p>
            <p><%= number_to_currency product.price %></p>
            <p><%= product.description %></p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>